### ISSUE TITLE
Extension at Open VSX Registry

### ISSUE THREAD

**Issue by DCsunset** [mdx-js/vscode-mdx#177]
### Subject of the feature

Open VSX is a vendor-neutral open-source alternative to the Visual Studio Marketplace. Code - OSS and VSCodium both use this registry.

### Problem

This extension is not available at Open VSX now.

### Expected behavior

It would be great if this extension could be added to Open VSX.

**Comment by JounQin** [comment]
It's already available at https://open-vsx.org/extension/unifiedjs/vscode-mdx now.
