### ISSUE TITLE
OOM Issues when paired with eslint-plugin-mdx@v2

### ISSUE THREAD

**Issue by mshick** [mdx-js/vscode-mdx#206]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

vscode-mdx v0.2.3, eslint-plugin-mdx v2.0.1

### Steps to reproduce

1. Pull this reproduction: https://github.com/mshick/eslint-mdx-next
2. Install the suggested VSCode extensions, `dbaeumer.vscode-eslint`, and `jounqin.vscode-mdx`.
3. Run `npm install`
4. Open your `ESLint` outputs panel. Notice that soon there are OOM errors and the server will crash.
5. Running `npm run eslint` has no issues and will find lint added to the `test.mdx` file.

Note: This picks up a [discussion I opened here](https://github.com/orgs/mdx-js/discussions/2071), now that I've confirmed the issue only occurs in `vscode-mdx` with `eslint-plugin-mdx@v2` and since `eslint-plugin-mdx@v2` appears to be working correctly.

Note: I've disabled all extensions except for `vscode-eslint` and `vscode-mdx` to ensure there were not conflicts.

Here is my VSCode build info:

```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:37.209Z (3 wks ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```

### Expected behavior

No OOM errors should happen. The eslint server should stay running.

### Actual behavior

The server crashes.

```
...
<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal javascript OOM in GC during deserialization
#

[Info  - 3:29:29 PM] Connection to server got closed. Server will restart.
[Info  - 3:29:29 PM] ESLint server stopped.
[Info  - 3:29:29 PM] ESLint server is starting
[Info  - 3:29:29 PM] ESLint server running in node v16.13.0
[Info  - 3:29:29 PM] ESLint server is running.
[Info  - 3:29:30 PM] ESLint library loaded from: /Users/mshick/Code/mshick/eslint-mdx-next/nextjs-blog/node_modules/eslint/lib/api.js

<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal javascript OOM in GC during deserialization
#

[Error - 3:29:38 PM] The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Info  - 3:29:38 PM] ESLint server stopped.
```

### Runtime

Node v16

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by JounQin** [comment]
```json
{
  "eslint.runtime": "node"
}
```

See https://github.com/mdx-js/vscode-mdx#known-vscode-eslint-issues

**Comment by mshick** [comment]
@JounQin That did it! Really appreciate the help.
