### ISSUE TITLE
Deprecate `silvenon.mdx`

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/vscode-mdx#215]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

This plugin was originally created and released by @silvenon. It was later moved to the unifiedjs organization. The old one has many more downloads. These users won’t receive any updates.

### Solution

Register `silvenon.mdx` as deprecated in favour of `unifiedjs.vscode-mdx`. https://github.com/microsoft/vscode-discussions/discussions/1.

Anyone could do this, but it would be nice to give @silvenon a chance to do so first, as it’s their extension.

### Alternatives

It could be unpublished as well, but deprecation offers a friendlier migration path for existing users.

**Comment by silvenon** [comment]
https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-3340102

**Comment by silvenon** [comment]
> It was later moved to the unifiedjs organization.

Just to correct this, the two extensions were created independently of each other, AFAIK.

**Comment by silvenon** [comment]
I released a patch version of my extension making it clear that it's deprecated. Hopefully the VS Code team will mark it as such in the Marketplace soon. 🤞

<img width="648" alt="Screenshot 2022-08-08 at 21 48 51" src="https://user-images.githubusercontent.com/471278/183502139-661d4235-7125-46cd-a5de-d8e6428d7a83.png">

**Comment by silvenon** [comment]
Update: VS Code marked my extension as deprecated in the Marketplace, it will take some time for it to propagate.
