### ISSUE TITLE
VS Code extension: Extra closing backticks

### ISSUE THREAD

**Issue by robdodson** [mdx-js/vscode-mdx#231]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v1.0.3

### Steps to reproduce

- With the VS Code extension enabled
- Type a backtick at the beginning of a word, and another at the end of the word.

See included video:

https://user-images.githubusercontent.com/1066253/199880749-eb13dcfb-60a3-42b1-b016-1a8a625458f1.mp4

### Expected behavior

- There should be one backtick at the beginning of the word, and one backtick at the end of the word.

### Actual behavior

- There are two backticks at the end of the word

**Comment by TomasHubelbauer** [comment]
FYI this extends to code blocks as well:

https://user-images.githubusercontent.com/6831144/220158995-78af9321-997a-457e-abaf-6cdce9b05666.mov

**Comment by TomasHubelbauer** [comment]
@robdodson feel free to check out my PR to see if it fixes your issue.
