### ISSUE TITLE
Support remark syntax plugins in `@mdx-js/monaco`

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/vscode-mdx#264]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The language service was written with support for remark/micromark syntax plugins in mind, but not the Monaco editor integration.

The language service is used in a web worker. Since unified plugins are functions, they can’t be passed from the main thread to the worker. This means the user will need to define a custom worker in order to use remark plugins.

### Solution

Mimic https://github.com/remcohaszing/monaco-tailwindcss to allow users to define a custom worker and inject options.

### Alternatives

:shrug:

**Comment by ChristianMurphy** [comment]
It may be possible for the main thread and worker to talk via a proxy sending requests between the two.

Which is how https://partytown.builder.io/ works.
https://partytown.builder.io/how-does-partytown-work gives background on the approach.

**Comment by remcohaszing** [comment]
Yes, that’s how Monaco editor works as well. The problem is we can’t pass functions (like unified plugins), because they aren’t supported by the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm).

It’s not a big deal. I dealt with it before in `monaco-tailwindcss` and `monaco-unified`, but it makes usage a bit quirky.

**Comment by ChristianMurphy** [comment]
Partytown's approach may be able to help:

> Data passed between the main thread and web worker must be [serializable](https://en.wikipedia.org/wiki/Serialization). Partytown automatically handles the serializing and deserializing of data passed between threads. This works for primitive values, such as a `string`, `boolean` or `number`, and **also functions, which get unique IDs assigned that are passed to the opposite thread and can be called.**

https://partytown.builder.io/how-does-partytown-work

**Comment by ChristianMurphy** [comment]
The source implementing function serializing/proxy support https://github.com/BuilderIO/partytown/blob/main/src/lib/web-worker/worker-serialization.ts

**Comment by remcohaszing** [comment]
It appears Partytown requires even more configuration of the build tool. In my experience maintaining various Monaco editor related projects, this is the part users struggle with. Partytown really looks like a cool project, but I don’t think having a library depend on it is a good choice.

The difference when using the approach by `monaco-tailwindcss`, is this (This works with Webpack and Vite. Exact usage depends on the build tool.):

```diff
  window.MonacoEnvironment = {
    getWorker(moduleId, label) {
      switch (label) {
        case 'editorWorkerService':
          return new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker', import.meta.url))
        case 'css':
        case 'less':
        case 'scss':
          return new Worker(new URL('monaco-editor/esm/vs/language/css/css.worker', import.meta.url))
        case 'handlebars':
        case 'html':
        case 'razor':
          return new Worker(new URL('monaco-editor/esm/vs/language/html/html.worker', import.meta.url))
        case 'json':
          return new Worker(new URL('monaco-editor/esm/vs/language/json/json.worker', import.meta.url))
        case 'mdx':
-         return new Worker(new URL('@mdx-js/monaco/mdx.worker', import.meta.url))
+         return new Worker(new URL('./mdx.worker', import.meta.url))
        case 'javascript':
        case 'typescript':
          return new Worker(new URL('monaco-editor/esm/vs/language/typescript/ts.worker', import.meta.url))
        default:
          throw new Error(`Unknown label ${label}`)
      }
    }
  };
```

and the addition of this file:

```js
import { initialize } from '@mdx-js/mdx.worker'
import remarkFrontmatter from 'remark-frontmatter'
import remarkGfm from 'remark-gfm'

initialize({
  plugins: [remarkFrontmatter, remarkGfm]
})
```
