### ISSUE TITLE
Rename `Markdown React` language to `MDX`

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/vscode-mdx#280]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently the language for MDX files is called `Markdown React` (id: `mdx`). This name, but not id, is consistent the the VSCode builting languages `JavaScript React` (id: `javascriptreact`) and `TypeScript React` (id: `typescriptreact`), which represent `.jsx` and `.tsx` files.

Personally I don’t like that name. It suggests the language is bound to React, but there are more JSX implementations. Also the id isn’t consistent with the name.

### Solution

Rename the language name to `MDX`.

### Alternatives

Keep it as-is.

Not an alternative IMO is renaming the language id, because other extensions already rely on it.

**Comment by wooorm** [comment]
Same. I don’t think MDX is just `Markdown + React`. Or even `Markdown + JS(X)`.

Maybe a bit annoying to have the name and ID drift apart. If we can change, better to do it now. No strong feelings on it though, you can choose!

**Comment by remcohaszing** [comment]
It doesn’t drift the name and ID apart. It actually aligns them.
