### ISSUE TITLE
Support frontmatter

### ISSUE THREAD

**Issue by adueck** [mdx-js/vscode-mdx#296]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

First of all thank you @remcohaszing so much for all your work on the language server. This morning I went out on a limb and searched to see if there was any work being done for TypeScript intellisense with mdx. I was so delighted to see you work on this. Thank you!

### Problem

Adding [frontmatter](https://mdxjs.com/guides/frontmatter/) to an .mdx file

```markdown
---
title: Hi, World!
---

# Hi, World!
```

throws the following extension error:

```
Request textDocument/foldingRange failed.
```

This keeps popping up while typing in VSCode.

### Solution

It would be great if [mdx frontmatter](https://mdxjs.com/guides/frontmatter/) would be allowed, because it is a super common part of the markdown/mdx workflow.

I assume this would be taken care of with [#295](]https://github.com/mdx-js/vscode-mdx/issues/295).

### Alternatives

Not sure.

**Comment by adueck** [comment]
Oh sorry I just saw that this would probably be taken care of by [#295](https://github.com/mdx-js/vscode-mdx/issues/295)?

**Comment by ChristianMurphy** [comment]
@adueck have you tried version 1.2.0 or newer?
Syntax plugin are already supported from the remark configuration. https://github.com/mdx-js/vscode-mdx/pull/272

**Comment by adueck** [comment]
@ChristianMurphy Oh yes, sorry I should have read that in the documentation first. It workse!
