### ISSUE TITLE
IntelliSense not working

### ISSUE THREAD

**Issue by kevinwolfdev** [mdx-js/vscode-mdx#56]
Hey! So far this plugin has been excellent, but IntelliSense is not working for me. Any ideas on how can I enable it?

**Comment by JounQin** [comment]
Yes, I'm sorry that hasn't been supported yet, will try to integrate with IntelliSense from js/jsx someday soon, but I'm not so familiar with it actually.

**Comment by iamkevinwolf** [comment]
Ok, I can do some research and will be happy to drop a PR.

**Comment by peterlawless** [comment]
Intellisense (e.g., import autocomplete) is still not working for me.  Are there any plans to implement it in the future?

**Comment by ChristianMurphy** [comment]
@peterlawless PRs adding Intellisense support are welcome

**Comment by ebellumat** [comment]
I'm still loocking for it
